spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    static-path-pattern: /resources/**

logging:
  level:
    org:
      springframework:
        web: DEBUG
